version: "3.7"

services:  
  sql-server-db:
    container_name: sql-server-db  
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
    - cnab_network

  srv-cnab:
    container_name: srv-cnab
    build:
      context: ./srv-cnab
      dockerfile: Dockerfile  
    links:
      - sql-server-db
    environment:
      - DATABASE_SERVIDOR=sql-server-db
      - DATABASE_USUARIO=sa
      - DATABASE_SENHA=Pass@word
      - DATABASE=db_desafio_dev
    ports:
      - "8080:8080"
    volumes:
      - logs:/usr/src/app/logs
    networks:
    - cnab_network

volumes:
  mssqldata:
  logs:

networks:
  cnab_network: