version: "3.7"

services:  
  sql-server-db:
    container_name: sql-server-db  
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
    - cnab_network

volumes:
  mssqldata:

networks:
  cnab_network: